---
- hosts: 172.31.34.135
  become: yes
  tasks: 
  - name: i want to excute direct linux command
    command: hostname -f
    register: myresult
  - name: i want to display first task result
    debug:
      msg: "{{myresult}}"  