---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"  

  - name: i want to start apache2
    service: 
      name: "{{apache2mywebpackonubuntu}}"
      state: restarted    
    when: ansible_os_family =="Debian"  

  - name: i want to install webserver on redHat nodes
    yum:
      name: "{{webpackonredHat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start webserver
    service: 
      name: "{{webpackonredHat}}"
      state: started
    when: ansible_os_family =="RedHat"
     
    
       